# Generated by Django 4.1.2 on 2022-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Расскажите немного о себе', max_length=500, null=True, verbose_name='Биография пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Введите имя пользователя', max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Введите фамилию пользователя', max_length=100, null=True, verbose_name='Фамилия пользователя'),
        ),
    ]
