# Generated by Django 4.1.2 on 2022-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(help_text='Введите имя пользователя', max_length=100, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию пользователя', max_length=100, null=True, verbose_name='Фамилия пользователя'),
        ),
    ]
