# Generated by Django 4.1.2 on 2022-10-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Сделайте запись в дневник', max_length=500, verbose_name='Запись в дневнике')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PostInDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.post')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название дневника', max_length=20, verbose_name='Название дневника')),
                ('posts', models.ForeignKey(help_text='Сделайте запись в дневник', on_delete=django.db.models.deletion.CASCADE, to='diary.postindiary', verbose_name='Запись в дневнике')),
            ],
        ),
    ]
