# Generated by Django 4.1.2 on 2022-10-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='posts',
            field=models.ForeignKey(help_text='Сделайте запись в дневник', null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.postindiary', verbose_name='Запись в дневнике'),
        ),
    ]
