# Generated by Django 4.1.2 on 2022-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diary_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='posts',
        ),
        migrations.AddField(
            model_name='diary',
            name='posts',
            field=models.ManyToManyField(blank=True, to='diary.post'),
        ),
    ]
