# Generated by Django 4.1.2 on 2022-10-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diary_posts_diary_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostInDiary',
        ),
    ]
