# Generated by Django 4.1.2 on 2022-10-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Моя заметка', help_text='Напишите заголовок заметки', max_length=30, verbose_name='Заголовок заметки'),
        ),
    ]
