# Generated by Django 4.1.2 on 2022-10-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_changed',
            field=models.BooleanField(default=False, verbose_name='Была ли редактирована заметка'),
        ),
    ]
